# Generated by Django 4.1 on 2022-08-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broodjeshuis',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='walvis',
            name='lastname',
        ),
    ]
