# Generated by Django 4.1 on 2022-08-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellen', '0002_remove_broodjeshuis_lastname_remove_walvis_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='broodjeshuis',
            name='keuze',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walvis',
            name='keuze',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
