# Generated by Django 4.1 on 2022-08-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellen', '0003_broodjeshuis_keuze_walvis_keuze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broodjeshuis',
            old_name='keuze',
            new_name='keuzes',
        ),
        migrations.RenameField(
            model_name='walvis',
            old_name='keuze',
            new_name='keuzes',
        ),
    ]
